
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-client
  template:
    metadata:
      labels:
        app: bot-client
    spec:
      containers:
        - name: bot-client
          image: gtinside/bot-client:latest
      containers:
        - name: bot-server
          image: gtinside/bot-server:latest
          env:
            - name: SUBSCRIPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: subscription-key
                  key: subscription-key
            - name: ANYSCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anyscale-api-key
                  key: anyscale-api-key

---

apiVersion: v1
kind: Service
metadata:
  name: bot-client-service
spec:
  type: NodePort
  selector:
    app: bot-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: bot-server-service
spec:
  selector:
    app: bot-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
